/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LoginRouteImport } from './routes/login'
import { Route as GerandoRouteImport } from './routes/gerando'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppTreinoRouteImport } from './routes/_app.treino'
import { Route as AppPlanosRouteImport } from './routes/_app.planos'
import { Route as AppPerfilRouteImport } from './routes/_app.perfil'
import { Route as AppEvolucaoRouteImport } from './routes/_app.evolucao'
import { Route as AppDietaRouteImport } from './routes/_app.dieta'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppAguaRouteImport } from './routes/_app.agua'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const GerandoRoute = GerandoRouteImport.update({
  id: '/gerando',
  path: '/gerando',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppTreinoRoute = AppTreinoRouteImport.update({
  id: '/treino',
  path: '/treino',
  getParentRoute: () => AppRoute,
} as any)
const AppPlanosRoute = AppPlanosRouteImport.update({
  id: '/planos',
  path: '/planos',
  getParentRoute: () => AppRoute,
} as any)
const AppPerfilRoute = AppPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => AppRoute,
} as any)
const AppEvolucaoRoute = AppEvolucaoRouteImport.update({
  id: '/evolucao',
  path: '/evolucao',
  getParentRoute: () => AppRoute,
} as any)
const AppDietaRoute = AppDietaRouteImport.update({
  id: '/dieta',
  path: '/dieta',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppAguaRoute = AppAguaRouteImport.update({
  id: '/agua',
  path: '/agua',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/gerando': typeof GerandoRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/signup': typeof SignupRoute
  '/agua': typeof AppAguaRoute
  '/dashboard': typeof AppDashboardRoute
  '/dieta': typeof AppDietaRoute
  '/evolucao': typeof AppEvolucaoRoute
  '/perfil': typeof AppPerfilRoute
  '/planos': typeof AppPlanosRoute
  '/treino': typeof AppTreinoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/gerando': typeof GerandoRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/signup': typeof SignupRoute
  '/agua': typeof AppAguaRoute
  '/dashboard': typeof AppDashboardRoute
  '/dieta': typeof AppDietaRoute
  '/evolucao': typeof AppEvolucaoRoute
  '/perfil': typeof AppPerfilRoute
  '/planos': typeof AppPlanosRoute
  '/treino': typeof AppTreinoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/gerando': typeof GerandoRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/signup': typeof SignupRoute
  '/_app/agua': typeof AppAguaRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/dieta': typeof AppDietaRoute
  '/_app/evolucao': typeof AppEvolucaoRoute
  '/_app/perfil': typeof AppPerfilRoute
  '/_app/planos': typeof AppPlanosRoute
  '/_app/treino': typeof AppTreinoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/gerando'
    | '/login'
    | '/onboarding'
    | '/signup'
    | '/agua'
    | '/dashboard'
    | '/dieta'
    | '/evolucao'
    | '/perfil'
    | '/planos'
    | '/treino'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/gerando'
    | '/login'
    | '/onboarding'
    | '/signup'
    | '/agua'
    | '/dashboard'
    | '/dieta'
    | '/evolucao'
    | '/perfil'
    | '/planos'
    | '/treino'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/gerando'
    | '/login'
    | '/onboarding'
    | '/signup'
    | '/_app/agua'
    | '/_app/dashboard'
    | '/_app/dieta'
    | '/_app/evolucao'
    | '/_app/perfil'
    | '/_app/planos'
    | '/_app/treino'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  GerandoRoute: typeof GerandoRoute
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gerando': {
      id: '/gerando'
      path: '/gerando'
      fullPath: '/gerando'
      preLoaderRoute: typeof GerandoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/treino': {
      id: '/_app/treino'
      path: '/treino'
      fullPath: '/treino'
      preLoaderRoute: typeof AppTreinoRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/planos': {
      id: '/_app/planos'
      path: '/planos'
      fullPath: '/planos'
      preLoaderRoute: typeof AppPlanosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/perfil': {
      id: '/_app/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof AppPerfilRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/evolucao': {
      id: '/_app/evolucao'
      path: '/evolucao'
      fullPath: '/evolucao'
      preLoaderRoute: typeof AppEvolucaoRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dieta': {
      id: '/_app/dieta'
      path: '/dieta'
      fullPath: '/dieta'
      preLoaderRoute: typeof AppDietaRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/agua': {
      id: '/_app/agua'
      path: '/agua'
      fullPath: '/agua'
      preLoaderRoute: typeof AppAguaRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAguaRoute: typeof AppAguaRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppDietaRoute: typeof AppDietaRoute
  AppEvolucaoRoute: typeof AppEvolucaoRoute
  AppPerfilRoute: typeof AppPerfilRoute
  AppPlanosRoute: typeof AppPlanosRoute
  AppTreinoRoute: typeof AppTreinoRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAguaRoute: AppAguaRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppDietaRoute: AppDietaRoute,
  AppEvolucaoRoute: AppEvolucaoRoute,
  AppPerfilRoute: AppPerfilRoute,
  AppPlanosRoute: AppPlanosRoute,
  AppTreinoRoute: AppTreinoRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  GerandoRoute: GerandoRoute,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
